
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int AND = 3;
  public static final int GE = 8;
  public static final int BOOL_LIT = 16;
  public static final int EQ = 13;
  public static final int EOF = 0;
  public static final int LE = 9;
  public static final int ID = 14;
  public static final int GT = 10;
  public static final int error = 1;
  public static final int SEMICOLON = 2;
  public static final int RPAREN = 7;
  public static final int NOT = 5;
  public static final int NE = 12;
  public static final int LT = 11;
  public static final int LPAREN = 6;
  public static final int INT_LIT = 15;
  public static final int OR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "GE",
  "LE",
  "GT",
  "LT",
  "NE",
  "EQ",
  "ID",
  "INT_LIT",
  "BOOL_LIT"
  };
}

