/* The following code was generated by JFlex 1.7.0 */


package Scanner;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;

import Parser.ParserSym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\4\1\11\1\11\1\5\22\0\1\6\1\45\1\7"+
    "\2\0\1\52\1\53\1\0\1\36\1\37\1\13\1\50\1\43\1\51"+
    "\1\0\1\12\1\1\11\2\1\0\1\42\1\47\1\44\1\46\2\0"+
    "\32\3\1\0\1\10\2\0\1\3\1\0\1\55\1\25\1\34\1\24"+
    "\1\31\1\32\1\21\1\30\1\17\2\3\1\26\1\3\1\20\1\23"+
    "\1\35\1\3\1\16\1\14\1\15\1\33\1\22\1\27\3\3\1\40"+
    "\1\54\1\41\7\0\1\11\u1fa2\0\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\4\1\1\1\5\1\6"+
    "\12\3\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\2\1\1\0"+
    "\1\24\1\0\1\25\1\0\4\3\1\26\7\3\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\0\3\3\1\35"+
    "\10\3\1\25\1\3\1\36\2\3\1\37\1\3\1\40"+
    "\1\3\1\41\1\42\3\3\1\43\1\3\1\44\1\45"+
    "\1\46\1\47\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\56\0\134\0\212\0\270\0\56\0\346"+
    "\0\u0114\0\56\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228"+
    "\0\u0256\0\u0284\0\u02b2\0\u02e0\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\u030e\0\u033c\0\u036a\0\u0398\0\56\0\56"+
    "\0\56\0\u03c6\0\u03f4\0\346\0\56\0\u0422\0\u0450\0\u047e"+
    "\0\u04ac\0\u04da\0\u0508\0\u0536\0\212\0\u0564\0\u0592\0\u05c0"+
    "\0\u05ee\0\u061c\0\u064a\0\u0678\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\u06a6\0\u06d4\0\u0702\0\u0730\0\212\0\u075e"+
    "\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\56"+
    "\0\u08ce\0\212\0\u08fc\0\u092a\0\212\0\u0958\0\212\0\u0986"+
    "\0\212\0\212\0\u09b4\0\u09e2\0\u0a10\0\212\0\u0a3e\0\212"+
    "\0\212\0\212\0\212\0\212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\2\2"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\2\5\1\17"+
    "\1\20\1\5\1\21\1\5\1\22\1\5\1\23\1\24"+
    "\3\5\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\5\57\0\2\4\54\0\3\5\10\0\22\5\17\0"+
    "\1\5\5\0\1\7\50\0\4\44\2\0\1\44\1\45"+
    "\1\46\45\44\12\0\1\47\1\50\43\0\3\5\10\0"+
    "\1\5\1\51\20\5\17\0\1\5\1\0\3\5\10\0"+
    "\2\5\1\52\17\5\17\0\1\5\1\0\3\5\10\0"+
    "\15\5\1\53\4\5\17\0\1\5\1\0\3\5\10\0"+
    "\4\5\1\54\11\5\1\55\3\5\17\0\1\5\1\0"+
    "\3\5\10\0\7\5\1\56\12\5\17\0\1\5\1\0"+
    "\3\5\10\0\17\5\1\57\2\5\17\0\1\5\1\0"+
    "\3\5\10\0\7\5\1\60\12\5\17\0\1\5\1\0"+
    "\3\5\10\0\14\5\1\61\5\5\17\0\1\5\1\0"+
    "\3\5\10\0\12\5\1\62\7\5\17\0\1\5\1\0"+
    "\3\5\10\0\17\5\1\63\2\5\17\0\1\64\44\0"+
    "\1\65\55\0\1\66\55\0\1\67\55\0\1\70\64\0"+
    "\1\71\56\0\1\72\1\0\4\44\2\0\3\44\1\0"+
    "\44\44\4\47\2\0\50\47\12\50\1\0\1\73\42\50"+
    "\1\0\3\5\10\0\2\5\1\74\17\5\17\0\1\5"+
    "\1\0\3\5\10\0\17\5\1\75\2\5\17\0\1\5"+
    "\1\0\3\5\10\0\1\5\1\76\20\5\17\0\1\5"+
    "\1\0\3\5\10\0\1\5\1\77\17\5\1\100\17\0"+
    "\1\5\1\0\3\5\10\0\3\5\1\101\16\5\17\0"+
    "\1\5\1\0\3\5\10\0\1\5\1\102\20\5\17\0"+
    "\1\5\1\0\3\5\10\0\7\5\1\103\12\5\17\0"+
    "\1\5\1\0\3\5\10\0\3\5\1\104\16\5\17\0"+
    "\1\5\1\0\3\5\10\0\1\105\21\5\17\0\1\5"+
    "\1\0\3\5\10\0\4\5\1\106\15\5\17\0\1\5"+
    "\1\0\3\5\10\0\12\5\1\107\7\5\17\0\1\5"+
    "\12\50\1\110\1\73\42\50\1\0\3\5\10\0\3\5"+
    "\1\111\16\5\17\0\1\5\1\0\3\5\10\0\15\5"+
    "\1\112\4\5\17\0\1\5\1\0\3\5\10\0\17\5"+
    "\1\113\2\5\17\0\1\5\1\0\3\5\10\0\17\5"+
    "\1\114\2\5\17\0\1\5\1\0\3\5\10\0\10\5"+
    "\1\115\11\5\17\0\1\5\1\0\3\5\10\0\21\5"+
    "\1\116\17\0\1\5\1\0\3\5\10\0\12\5\1\117"+
    "\7\5\17\0\1\5\1\0\3\5\10\0\12\5\1\120"+
    "\7\5\17\0\1\5\1\0\3\5\10\0\15\5\1\121"+
    "\4\5\17\0\1\5\1\0\3\5\10\0\20\5\1\122"+
    "\1\5\17\0\1\5\1\0\3\5\10\0\1\123\21\5"+
    "\17\0\1\5\1\0\3\5\10\0\4\5\1\124\15\5"+
    "\17\0\1\5\1\0\3\5\10\0\2\5\1\125\17\5"+
    "\17\0\1\5\1\0\3\5\10\0\1\5\1\126\20\5"+
    "\17\0\1\5\1\0\3\5\10\0\17\5\1\127\2\5"+
    "\17\0\1\5\1\0\3\5\10\0\15\5\1\130\4\5"+
    "\17\0\1\5\1\0\3\5\10\0\15\5\1\131\4\5"+
    "\17\0\1\5\1\0\3\5\10\0\5\5\1\132\14\5"+
    "\17\0\1\5\1\0\3\5\10\0\4\5\1\133\15\5"+
    "\17\0\1\5\1\0\3\5\10\0\1\5\1\134\20\5"+
    "\17\0\1\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2668];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\1\11\12\1\6\11"+
    "\4\1\3\11\2\1\1\0\1\11\1\0\1\1\1\0"+
    "\14\1\6\11\1\0\14\1\1\11\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol getSymbol(int type) {
        return new ComplexSymbol(ParserSym.terminalNames[type], type);
    }
    
    private Symbol getSymbol(int type, Object value) {
        return new ComplexSymbol(ParserSym.terminalNames[type], type, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
        /* Qué hacer cuando llega a EOF */
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return getSymbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error léxico: "+yytext());
            } 
            // fall through
          case 41: break;
          case 2: 
            { return getSymbol(ParserSym.INT_LIT, Integer.parseInt(yytext()));
            } 
            // fall through
          case 42: break;
          case 3: 
            { return getSymbol(ParserSym.ID, yytext());
            } 
            // fall through
          case 43: break;
          case 4: 
            { /* white space */
            } 
            // fall through
          case 44: break;
          case 5: 
            { return getSymbol(ParserSym.DIV,yytext());
            } 
            // fall through
          case 45: break;
          case 6: 
            { return getSymbol(ParserSym.MULT,yytext());
            } 
            // fall through
          case 46: break;
          case 7: 
            { return getSymbol(ParserSym.LPAREN);
            } 
            // fall through
          case 47: break;
          case 8: 
            { return getSymbol(ParserSym.RPAREN);
            } 
            // fall through
          case 48: break;
          case 9: 
            { return getSymbol(ParserSym.LCURL);
            } 
            // fall through
          case 49: break;
          case 10: 
            { return getSymbol(ParserSym.RCURL);
            } 
            // fall through
          case 50: break;
          case 11: 
            { return getSymbol(ParserSym.SEMICOLON);
            } 
            // fall through
          case 51: break;
          case 12: 
            { return getSymbol(ParserSym.COMMA);
            } 
            // fall through
          case 52: break;
          case 13: 
            { return getSymbol(ParserSym.ASSIGN,yytext());
            } 
            // fall through
          case 53: break;
          case 14: 
            { return getSymbol(ParserSym.NOT);
            } 
            // fall through
          case 54: break;
          case 15: 
            { return getSymbol(ParserSym.GT,yytext());
            } 
            // fall through
          case 55: break;
          case 16: 
            { return getSymbol(ParserSym.LT,yytext());
            } 
            // fall through
          case 56: break;
          case 17: 
            { return getSymbol(ParserSym.SUM,yytext());
            } 
            // fall through
          case 57: break;
          case 18: 
            { return getSymbol(ParserSym.SUB,yytext());
            } 
            // fall through
          case 58: break;
          case 19: 
            { return getSymbol(ParserSym.MOD,yytext());
            } 
            // fall through
          case 59: break;
          case 20: 
            { return getSymbol(ParserSym.STR_LIT, yytext());
            } 
            // fall through
          case 60: break;
          case 21: 
            { 
            } 
            // fall through
          case 61: break;
          case 22: 
            { return getSymbol(ParserSym.IF);
            } 
            // fall through
          case 62: break;
          case 23: 
            { return getSymbol(ParserSym.EQ,yytext());
            } 
            // fall through
          case 63: break;
          case 24: 
            { return getSymbol(ParserSym.NE,yytext());
            } 
            // fall through
          case 64: break;
          case 25: 
            { return getSymbol(ParserSym.GE,yytext());
            } 
            // fall through
          case 65: break;
          case 26: 
            { return getSymbol(ParserSym.LE,yytext());
            } 
            // fall through
          case 66: break;
          case 27: 
            { return getSymbol(ParserSym.AND);
            } 
            // fall through
          case 67: break;
          case 28: 
            { return getSymbol(ParserSym.OR);
            } 
            // fall through
          case 68: break;
          case 29: 
            { return getSymbol(ParserSym.INT_TYPE,yytext());
            } 
            // fall through
          case 69: break;
          case 30: 
            { return getSymbol(ParserSym.BOOL_LIT, new Boolean(true));
            } 
            // fall through
          case 70: break;
          case 31: 
            { return getSymbol(ParserSym.VOID_TYPE,yytext());
            } 
            // fall through
          case 71: break;
          case 32: 
            { return getSymbol(ParserSym.BOOL_TYPE,yytext());
            } 
            // fall through
          case 72: break;
          case 33: 
            { return getSymbol(ParserSym.ELSE);
            } 
            // fall through
          case 73: break;
          case 34: 
            { return getSymbol(ParserSym.FUNC);
            } 
            // fall through
          case 74: break;
          case 35: 
            { return getSymbol(ParserSym.INPUT);
            } 
            // fall through
          case 75: break;
          case 36: 
            { return getSymbol(ParserSym.WHILE);
            } 
            // fall through
          case 76: break;
          case 37: 
            { return getSymbol(ParserSym.BOOL_LIT, new Boolean(false));
            } 
            // fall through
          case 77: break;
          case 38: 
            { return getSymbol(ParserSym.STR_TYPE,yytext());
            } 
            // fall through
          case 78: break;
          case 39: 
            { return getSymbol(ParserSym.RETURN);
            } 
            // fall through
          case 79: break;
          case 40: 
            { return getSymbol(ParserSym.OUTPUT);
            } 
            // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
