/* The following code was generated by JFlex 1.7.0 */


package Scanner;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;

import Parser.ParserSym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\4\1\11\1\11\1\5\22\0\1\6\1\37\1\7"+
    "\2\0\1\44\1\45\1\0\1\47\1\50\1\13\1\42\1\0\1\43"+
    "\1\0\1\12\1\1\11\2\1\0\1\53\1\41\1\36\1\40\2\0"+
    "\32\3\1\0\1\10\2\0\1\3\1\0\1\54\1\25\1\34\1\24"+
    "\1\31\1\32\1\21\1\30\1\17\2\3\1\26\1\3\1\20\1\23"+
    "\1\35\1\3\1\16\1\14\1\15\1\33\1\22\1\27\3\3\1\51"+
    "\1\46\1\52\7\0\1\11\u1fa2\0\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\4\1\1\1\5\1\6"+
    "\12\3\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\1\1\16\1\17\1\20\1\21\1\22\1\0\1\23"+
    "\1\0\1\24\1\0\1\25\1\26\4\3\1\27\7\3"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\0\3\3\1\42\10\3\1\43\1\3"+
    "\1\44\2\3\1\45\1\3\1\46\1\3\1\47\1\50"+
    "\3\3\1\51\1\3\1\52\1\53\1\54\1\55\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\55\0\132\0\207\0\264\0\55\0\341"+
    "\0\u010e\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\u040b\0\55\0\u0438\0\u0465\0\55\0\55\0\55"+
    "\0\55\0\55\0\341\0\55\0\u0492\0\u04bf\0\u04ec\0\55"+
    "\0\55\0\u0519\0\u0546\0\u0573\0\u05a0\0\207\0\u05cd\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\55\0\55\0\u0708"+
    "\0\u0735\0\u0762\0\u078f\0\207\0\u07bc\0\u07e9\0\u0816\0\u0843"+
    "\0\u0870\0\u089d\0\u08ca\0\u08f7\0\55\0\u0924\0\207\0\u0951"+
    "\0\u097e\0\207\0\u09ab\0\207\0\u09d8\0\207\0\207\0\u0a05"+
    "\0\u0a32\0\u0a5f\0\207\0\u0a8c\0\207\0\207\0\207\0\207"+
    "\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\2\2"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\2\5\1\17"+
    "\1\20\1\5\1\21\1\5\1\22\1\5\1\23\1\24"+
    "\3\5\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\5"+
    "\56\0\2\4\53\0\3\5\10\0\22\5\16\0\1\5"+
    "\5\0\1\7\47\0\4\43\2\0\1\43\1\44\1\45"+
    "\44\43\12\0\1\46\1\47\22\0\1\50\54\0\1\51"+
    "\17\0\3\5\10\0\1\5\1\52\20\5\16\0\1\5"+
    "\1\0\3\5\10\0\2\5\1\53\17\5\16\0\1\5"+
    "\1\0\3\5\10\0\15\5\1\54\4\5\16\0\1\5"+
    "\1\0\3\5\10\0\4\5\1\55\11\5\1\56\3\5"+
    "\16\0\1\5\1\0\3\5\10\0\7\5\1\57\12\5"+
    "\16\0\1\5\1\0\3\5\10\0\17\5\1\60\2\5"+
    "\16\0\1\5\1\0\3\5\10\0\7\5\1\61\12\5"+
    "\16\0\1\5\1\0\3\5\10\0\14\5\1\62\5\5"+
    "\16\0\1\5\1\0\3\5\10\0\12\5\1\63\7\5"+
    "\16\0\1\5\1\0\3\5\10\0\17\5\1\64\2\5"+
    "\16\0\1\65\36\0\1\66\54\0\1\67\54\0\1\70"+
    "\54\0\1\71\54\0\1\72\3\0\1\73\50\0\1\74"+
    "\4\0\1\75\56\0\1\76\55\0\1\77\6\0\4\43"+
    "\2\0\3\43\1\0\43\43\4\46\2\0\47\46\12\47"+
    "\1\0\1\100\41\47\1\0\3\5\10\0\2\5\1\101"+
    "\17\5\16\0\1\5\1\0\3\5\10\0\17\5\1\102"+
    "\2\5\16\0\1\5\1\0\3\5\10\0\1\5\1\103"+
    "\20\5\16\0\1\5\1\0\3\5\10\0\1\5\1\104"+
    "\17\5\1\105\16\0\1\5\1\0\3\5\10\0\3\5"+
    "\1\106\16\5\16\0\1\5\1\0\3\5\10\0\1\5"+
    "\1\107\20\5\16\0\1\5\1\0\3\5\10\0\7\5"+
    "\1\110\12\5\16\0\1\5\1\0\3\5\10\0\3\5"+
    "\1\111\16\5\16\0\1\5\1\0\3\5\10\0\1\112"+
    "\21\5\16\0\1\5\1\0\3\5\10\0\4\5\1\113"+
    "\15\5\16\0\1\5\1\0\3\5\10\0\12\5\1\114"+
    "\7\5\16\0\1\5\12\47\1\115\1\100\41\47\1\0"+
    "\3\5\10\0\3\5\1\116\16\5\16\0\1\5\1\0"+
    "\3\5\10\0\15\5\1\117\4\5\16\0\1\5\1\0"+
    "\3\5\10\0\17\5\1\120\2\5\16\0\1\5\1\0"+
    "\3\5\10\0\17\5\1\121\2\5\16\0\1\5\1\0"+
    "\3\5\10\0\10\5\1\122\11\5\16\0\1\5\1\0"+
    "\3\5\10\0\21\5\1\123\16\0\1\5\1\0\3\5"+
    "\10\0\12\5\1\124\7\5\16\0\1\5\1\0\3\5"+
    "\10\0\12\5\1\125\7\5\16\0\1\5\1\0\3\5"+
    "\10\0\15\5\1\126\4\5\16\0\1\5\1\0\3\5"+
    "\10\0\20\5\1\127\1\5\16\0\1\5\1\0\3\5"+
    "\10\0\1\130\21\5\16\0\1\5\1\0\3\5\10\0"+
    "\4\5\1\131\15\5\16\0\1\5\1\0\3\5\10\0"+
    "\2\5\1\132\17\5\16\0\1\5\1\0\3\5\10\0"+
    "\1\5\1\133\20\5\16\0\1\5\1\0\3\5\10\0"+
    "\17\5\1\134\2\5\16\0\1\5\1\0\3\5\10\0"+
    "\15\5\1\135\4\5\16\0\1\5\1\0\3\5\10\0"+
    "\15\5\1\136\4\5\16\0\1\5\1\0\3\5\10\0"+
    "\5\5\1\137\14\5\16\0\1\5\1\0\3\5\10\0"+
    "\4\5\1\140\15\5\16\0\1\5\1\0\3\5\10\0"+
    "\1\5\1\141\20\5\16\0\1\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2745];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\23\1\1\11\2\1\5\11"+
    "\1\0\1\11\1\0\1\1\1\0\2\11\14\1\12\11"+
    "\1\0\14\1\1\11\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol getSymbol(int type) {
        return new ComplexSymbol(ParserSym.terminalNames[type], type);
    }
    
    private Symbol getSymbol(int type, Object value) {
        return new ComplexSymbol(ParserSym.terminalNames[type], type, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
        System.out.println("EOF");
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return getSymbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println(" ############## Error léxico: "+yytext());
            } 
            // fall through
          case 47: break;
          case 2: 
            { System.out.println("--> INT_LIT: "+yytext());
            } 
            // fall through
          case 48: break;
          case 3: 
            { System.out.println("--> ID: "+ yytext());
            } 
            // fall through
          case 49: break;
          case 4: 
            { /* white space */
            } 
            // fall through
          case 50: break;
          case 5: 
            { System.out.println("DIV");
            } 
            // fall through
          case 51: break;
          case 6: 
            { System.out.println("MULT");
            } 
            // fall through
          case 52: break;
          case 7: 
            { System.out.println("ASSIGN");
            } 
            // fall through
          case 53: break;
          case 8: 
            { System.out.println("NOT");
            } 
            // fall through
          case 54: break;
          case 9: 
            { System.out.println("GT");
            } 
            // fall through
          case 55: break;
          case 10: 
            { System.out.println("LT");
            } 
            // fall through
          case 56: break;
          case 11: 
            { System.out.println("SUM");
            } 
            // fall through
          case 57: break;
          case 12: 
            { System.out.println("SUB");
            } 
            // fall through
          case 58: break;
          case 13: 
            { System.out.println("MOD");
            } 
            // fall through
          case 59: break;
          case 14: 
            { System.out.println("LPAREN");
            } 
            // fall through
          case 60: break;
          case 15: 
            { System.out.println("RPAREN");
            } 
            // fall through
          case 61: break;
          case 16: 
            { System.out.println("LCURL");
            } 
            // fall through
          case 62: break;
          case 17: 
            { System.out.println("RCURL");
            } 
            // fall through
          case 63: break;
          case 18: 
            { System.out.println("SEMICOLON");
            } 
            // fall through
          case 64: break;
          case 19: 
            { System.out.println("--> STR_LIT: "+yytext());
            } 
            // fall through
          case 65: break;
          case 20: 
            { System.out.println("--> COMMENT2: "+yytext());
            } 
            // fall through
          case 66: break;
          case 21: 
            { System.out.println("DIV_ASSIGN");
            } 
            // fall through
          case 67: break;
          case 22: 
            { System.out.println("MULT_ASSIGN");
            } 
            // fall through
          case 68: break;
          case 23: 
            { System.out.println("IF");
            } 
            // fall through
          case 69: break;
          case 24: 
            { System.out.println("EQ");
            } 
            // fall through
          case 70: break;
          case 25: 
            { System.out.println("NOTEQ");
            } 
            // fall through
          case 71: break;
          case 26: 
            { System.out.println("GE");
            } 
            // fall through
          case 72: break;
          case 27: 
            { System.out.println("LE");
            } 
            // fall through
          case 73: break;
          case 28: 
            { System.out.println("SUM_ASSIGN");
            } 
            // fall through
          case 74: break;
          case 29: 
            { System.out.println("INC");
            } 
            // fall through
          case 75: break;
          case 30: 
            { System.out.println("SUB_ASSIGN");
            } 
            // fall through
          case 76: break;
          case 31: 
            { System.out.println("DEC");
            } 
            // fall through
          case 77: break;
          case 32: 
            { System.out.println("AND");
            } 
            // fall through
          case 78: break;
          case 33: 
            { System.out.println("OR");
            } 
            // fall through
          case 79: break;
          case 34: 
            { System.out.println("INT");
            } 
            // fall through
          case 80: break;
          case 35: 
            { System.out.println("--> COMMENT1: "+yytext());
            } 
            // fall through
          case 81: break;
          case 36: 
            { System.out.println("TRUE");
            } 
            // fall through
          case 82: break;
          case 37: 
            { System.out.println("VOID");
            } 
            // fall through
          case 83: break;
          case 38: 
            { System.out.println("BOOL");
            } 
            // fall through
          case 84: break;
          case 39: 
            { System.out.println("ELSE");
            } 
            // fall through
          case 85: break;
          case 40: 
            { System.out.println("FUNC");
            } 
            // fall through
          case 86: break;
          case 41: 
            { System.out.println("INPUT");
            } 
            // fall through
          case 87: break;
          case 42: 
            { System.out.println("WHILE");
            } 
            // fall through
          case 88: break;
          case 43: 
            { System.out.println("FALSE");
            } 
            // fall through
          case 89: break;
          case 44: 
            { System.out.println("STRING");
            } 
            // fall through
          case 90: break;
          case 45: 
            { System.out.println("RETURN");
            } 
            // fall through
          case 91: break;
          case 46: 
            { System.out.println("OUTPUT");
            } 
            // fall through
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
